### ISSUE TITLE
Problem to connect Homey to Mill account

### ISSUE THREAD

**Issue by pln8421** [glennsp/com.mill#1]
Hello Glenn
I have created MILL account.
When trying to connect Homey with this Mill account I get error message:

Unfortunately, we received an error from Mill:
Homey.app.authenticate is not a function.

Best regards Per

**Comment by pln8421** [comment]
I asked Mill if they changed the API or if it was down.
They did not answer this, Bashir said its a 3:rd party app in Beta and that I should speak with you.
My problem is I have ordered a couple of SG1200WIFI and it's not AV.. that was tested. 
My use case is to only run these with ATHomey so I need to know if the proposa is to get them or cancel the order. Not so urgent because planned delivery is 13:th of January.
I understand noone can promise anything but perhaps I can get a hint so I better know to take the risk or not.
Best regards, Per Larsson, Västerås Sweden

**Comment by glennsp** [comment]
This was an error introduced in version 1.0.1. This should be fixed in v1.0.2.

**Comment by glennsp** [comment]
Per Larsson,

I don't have any SGs to test, but I trust they will work the same way. Looks like the difference between AV and SG is wall-hanging vs stand-alone ovens? If you receive the ovens, I would be pleased if you could give me some feedback if they work or not, so I can update the "supported devices" for others to see as well.

**Comment by pln8421** [comment]
Hello Glenn.
They work as they should from Homey so you can add them to supported list.
Thanks for good support and have a nice day.

[image1.jpeg]

[image2.png]
Hälsningar Per in Västerås Sweden

21 dec. 2018 kl. 15:49 skrev Glenn S. Pedersen <notifications@github.com<mailto:notifications@github.com>>:


Per Larsson,

I don't have any SGs to test, but I trust they will work the same way. Looks like the difference between AV and SG is wall-hanging vs stand-alone ovens? If you receive the ovens, I would be pleased if you could give me some feedback if they work or not, so I can update the "supported devices" for others to see as well.
