### ISSUE TITLE
Can´t controll registered ovens - Screen appears blank.

### ISSUE THREAD

**Issue by Piddinygaard** [glennsp/com.mill#10]
I have now successfully added one oven to my Homey, but I am not able to controll it.

The oven appears in my "devices" panel, but when trying to enter the device, my screen goes blank. Ive added a picture for reference.

Unit: NE600WIFI
Phone: Iphone Xs Max

![53836664_779715835743267_398889169151066112_n](https://user-images.githubusercontent.com/48650939/54493053-fe171f80-48cb-11e9-8d37-602659a83f84.jpg)
![54434884_515394565651076_596256668887547904_n](https://user-images.githubusercontent.com/48650939/54493055-ff484c80-48cb-11e9-85af-96a70534633a.jpg)

**Comment by glennsp** [comment]
I've just updated the app to 1.0.4, fixing a few bugs. Could you see if you still experience this problem with the new version?

Thanks

**Comment by Piddinygaard** [comment]
Hi - this works fine now.
I updated the app, and now i´m able to controle all scenes as i should :)

Thanks!
