### ISSUE TITLE
Can't control mill ne1200 and ne900 thrue flows

### ISSUE THREAD

**Issue by Victorhomey** [glennsp/com.mill#12]
Hey,

First great app!

I have 2x ne1200 wifi 1x ne900 wifi 1x ne600 wifi. 

I can control them perfectly as it should individually. 

But when I want to control them thrue homey flows only the ne600wifi responds. The other heaters stay unchanged. 

Could you please help me?

It would also be great for the future if you could make flow cards for the whole house at once like you have in the mill app in the line next to the house's name. 

Thanks for the effort!

**Comment by slasktrat** [comment]
Same issue. Controlling through flows are unstable. Especially if adjusting more than one oven simultaneously.

**Comment by glennsp** [comment]
I've just pushed a new version as a beta, should be available in a day or two. Could you please test and see if it works as it should now?
