### ISSUE TITLE
Unable to locate app in new Homey Apps portal

### ISSUE THREAD

**Issue by joernnilsson** [glennsp/com.mill#14]
The new portal https://homey.app/en-gb/apps/ gives 0 results when searching for "Mill".

Maybe it excludes beta apps?

We are now unable to install the app on our Homey :( 

There's a ticket for this in Homey Support as well: https://community.athom.com/t/apps-missing-after-update-of-web-page/20635

**Comment by Gakk** [comment]
The previous URL returns 404 page not found:
https://apps.athom.com/app/com.mill

**Comment by joernnilsson** [comment]
I was able to install by building the app and deploying locally.

**Comment by Gakk** [comment]
@glennsp, I guess this is fixed now and the issue can be closed 😊

**Comment by glennsp** [comment]
Thanks. Documentation was updated and the app was back in the app store Nov 27.
