### ISSUE TITLE
Setting program mode should not be continuous

### ISSUE THREAD

**Issue by nlrb** [glennsp/com.mill#15]
First, thanks for the app, works pretty well :-).

The issue I have, however, is that when setting 'Program' mode, this is done as a continuous override. This makes that whichever mode is current in the program (e.g. comfort, sleep) is set continuous. The heater will not update modes according to the program.

Can you update in `mill.js` in the function `changeRoomMode` the parameter `always` to be only set when the mode is not program, i.e.
`always: (mode ? 1 : 0) // program (0) should not be an override`.

**Comment by glennsp** [comment]
Thanks!
