### ISSUE TITLE
Set mode doesn't work from flow

### ISSUE THREAD

**Issue by cortinaman** [glennsp/com.mill#3]
Hi

First of all, thumbs up for making a mill app. I've been waiting for this for some time.

I realize the app is still in beta mode, but I have some observations.

From the device faceplace I'm able to manipulate both temperature setpoint and thermostat mode from homey, I can select all modes and verify the selection in the native mill app on my phone.

Using the action cards in a flow I am able to adjust the setpoint, but selecting a mode is not transferred to the mill unit. This is in contrast to the homey app description which says thermostat mode can be set, but does not say anything about setpoint.

I want to make a forward regulating loop and turn the mill off when homey detects that the wood burning fireplace is lit, relying on a feedback loop is a bit slow due to the size of the room.

Homey version: 1.5.13
Mill homey app version: 1.0.2
Mill heater: 1000W glass list heater Gen 2: serial SKAHnnnnnn

Cheers, Frode

**Comment by glennsp** [comment]
Hi Frode,

thank you for spotting this, there was a small bug in the code.

I'ts been fixed and I've just submitted v1.0.3. Should be validated and out in a few days I hope.

-Glenn
