### ISSUE TITLE
Support for Mill Wi-Fi Sockets?

### ISSUE THREAD

**Issue by MartinBekkelund** [glennsp/com.mill#7]
Hi!

I have four Wi-Fi Sockets from Mill. Is there a chance for them to work with this app?

Best regards,

Martin

**Comment by glennsp** [comment]
Hi, I don't have any Mill Sockets at the moment, so I'm unable to try. As a first step, would you mind turning on debug logging (in the app config), try to pair and send me the debug log?

Thanks

**Comment by ekeskog** [comment]
I also have some mill wifi adapters. But that doesn't show up in the mill app.
Best regards
Roar

**Comment by spajder77** [comment]
I have 5 Mill Wi-Fi sockets and I have added all 5 to my Homey, and they are working fine and I have included them in flows.

**Comment by glennsp** [comment]
I got feedback that this works, so I'll close this thread.
