### ISSUE TITLE
Can't find NE600WIFI and NE1200WIFI

### ISSUE THREAD

**Issue by jumpingmushroom** [glennsp/com.mill#9]
I've got the NE600WIFI and NE1200WIFI mill heaters (the non-glass ones), but can't find them when trying to add the devices (No new devices have been found). Is there anything I can do to help out with getting this supported? Debug in the app settings report that the credentials are correct (Mill authenticated), so I guess that's not the issue.

**Comment by Piddinygaard** [comment]
I´ve successfully added one today, but can´t seem to add number two.

Both ovens are added in seperate rooms in the Mill app, and have been given seperate names. There is no special characters in any of the names or rooms.
The oven is marked as "online" in the Mill app, and remote works perfectly here.

**Comment by jumpingmushroom** [comment]
Ok, do you think there's a requirement that the ovens are in rooms? Right now mine are not assigned because that was a requirement when I was using them in home assistant, but I'm not sure how it is for this homey app.

I'll try to move the oven into a room and see if I can get it discovered then.

**Comment by Piddinygaard** [comment]
Could be!

My first oven NE600WIFI worked when added to a room i called "main bedroom".
Though the second NE600WIFI is not visible when trying to add ovens ...

**Comment by jumpingmushroom** [comment]
Turns out it was. Independent devices does not get discovered. Only devices added to rooms. I guess it makes sense if you want to use the profiles available for a room.

**Comment by Piddinygaard** [comment]
I have now also mounted a NE900WIFI and the same problem occurs. I added it to a new room "Stue/living room" and it does not appear in the Homey app when trying to add new device.

**Comment by glennsp** [comment]
Hi, I've just updated the version to 1.0.4 fixing a few bugs, including problems regarding adding devices. Could you please try the new version and see if it works as expected?

Thanks

**Comment by Piddinygaard** [comment]
Hi - this works fine now.
I updated the app, and were able to add them without problems.
